# Generated by Django 4.0.4 on 2022-06-14 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=200, verbose_name='nom_categorie')),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('pourcentage', models.IntegerField(blank=True, null=True, verbose_name='Pourcentage')),
            ],
            options={
                'verbose_name': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('sujet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services', verbose_name='Image')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Slug')),
                ('date_projet', models.CharField(max_length=100, verbose_name='Date projet')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('client', models.CharField(max_length=100, verbose_name='Client')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Desc1')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Portfolios_images', verbose_name='Image3')),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_categorie', to='app_web.categorie', verbose_name='Categorie')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'ordering': ['-created'],
            },
        ),
    ]
