# Generated by Django 4.1.1 on 2022-11-22 19:28

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Certification',
            },
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
                ('pourcentage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Competences',
            },
        ),
        migrations.CreateModel(
            name='CompetenceSuplementaire',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'CompetenceSuplementaire',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('sujet', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sujet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('formation', models.CharField(max_length=100)),
                ('ecole', models.CharField(blank=True, max_length=100, null=True)),
                ('periode', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('post', models.CharField(max_length=200)),
                ('entreprise', models.CharField(max_length=200)),
                ('periode', models.CharField(max_length=200)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('lien', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='FormationAttestee',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('periode', models.CharField(max_length=200)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'FormationAttestee',
            },
        ),
        migrations.CreateModel(
            name='Icone',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Icone',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('specialite', models.CharField(blank=True, max_length=200, null=True)),
                ('apropos', models.TextField(blank=True, null=True)),
                ('resume', django_quill.fields.QuillField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('naissance', models.DateField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=200, null=True)),
                ('disponibilite', models.CharField(blank=True, max_length=200, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('photoc', models.ImageField(blank=True, null=True, upload_to='avatar')),
                ('photo_bg', models.ImageField(blank=True, null=True, upload_to='avatar_bg')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram', models.CharField(blank=True, max_length=200, null=True)),
                ('linkdin', models.CharField(blank=True, max_length=200, null=True)),
                ('competence', models.TextField(blank=True, help_text='bref description', null=True)),
                ('langue', models.TextField(blank=True, help_text='bref description', null=True)),
                ('education', models.TextField(blank=True, help_text='bref description', null=True)),
                ('portfolio', models.TextField(blank=True, help_text='bref description', null=True)),
                ('experience', models.TextField(blank=True, help_text='bref description', null=True)),
                ('temoignage', models.TextField(blank=True, help_text='bref description', null=True)),
                ('contact', models.TextField(blank=True, help_text='bref description', null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv')),
            ],
            options={
                'verbose_name': 'Info',
            },
        ),
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Interet',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Langue',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, help_text='lien complet du site', max_length=100, null=True)),
                ('lien', models.URLField(blank=True, help_text='lien github', max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Portfolios_images')),
                ('categorie', models.CharField(blank=True, choices=[('filter-app', 'Securité'), ('filter-card', 'Desktop'), ('filter-web', 'Web')], default='first', max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Qualite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Qualite',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=200)),
                ('entreprise', models.CharField(blank=True, max_length=200, null=True)),
                ('periode', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Stage',
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('nom', models.CharField(max_length=200)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages')),
                ('specialite', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Temoignages',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True, null=True, verbose_name='Create date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services')),
                ('icone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_web.icone')),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['-updated'],
            },
        ),
    ]
