# Generated by Django 4.1.1 on 2022-11-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
