# Generated by Django 4.1.1 on 2022-11-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temoignage',
            old_name='statut',
            new_name='status',
        ),
    ]
