# Generated by Django 4.0.4 on 2022-06-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_alter_portfolio_date_projet_alter_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_projet',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Date projet'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Url'),
        ),
    ]
