# Generated by Django 4.1.1 on 2022-11-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0002_rename_statut_temoignage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
