# Generated by Django 4.1.1 on 2022-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_info_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categorie',
            field=models.CharField(blank=True, choices=[('filter-app', 'Securité'), ('filter-card', 'Desktop'), ('filter-web', 'Web')], default='first', max_length=100, null=True),
        ),
    ]
