# Generated by Django 4.0.6 on 2022-07-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0003_alter_portfolio_client_alter_portfolio_date_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competences',
            name='updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Create date'),
        ),
    ]
