# Generated by Django 4.1.1 on 2022-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0004_alter_portfolio_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='portfolio',
            field=models.TextField(blank=True, help_text='bref description', null=True),
        ),
    ]
