# Generated by Django 4.1.1 on 2022-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0006_certification_competencesuplementaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='ecole',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
