# Generated by Django 4.1.1 on 2022-11-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0007_alter_education_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
