# Generated by Django 4.1.1 on 2022-11-22 08:07

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0008_stage_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formationattestee',
            name='description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
