# Generated by Django 4.1.1 on 2022-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0009_alter_experience_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationattestee',
            name='site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
